#if !defined(COCG_SMOOTH_OPENMP_H_INCLUDED)
#define COCG_SMOOTH_OPENMP_H_INCLUDED

#if defined(COCG_DI_SMOOTH_OPENMP_H_INCLUDED)
  #define COCG_DI_SMOOTH_OPENMP_H_INCLUDED_REVERT
  #undef COCG_DI_SMOOTH_OPENMP_H_INCLUDED
#endif

#define COCG_Di_Smooth_OpenMP COCG_Smooth_OpenMP

#include "COCG_Di_Smooth_OpenMP.h"
#undef COCG_DI_SMOOTH_OPENMP_H_INCLUDED

#undef COCG_Di_Smooth_OpenMP

#if defined(COCG_DI_SMOOTH_OPENMP_H_INCLUDED_REVERT)
  #define COCG_DI_SMOOTH_OPENMP_H_INCLUDED
  #undef COCG_DI_SMOOTH_OPENMP_H_INCLUDED_REVERT
#endif

#endif // COCG_SMOOTH_OPENMP_H_INCLUDED
