#if !defined(COCG_DI_SMOOTH_MKL_H_INCLUDED)
#define COCG_DI_SMOOTH_MKL_H_INCLUDED

#if defined(COCG_LLT_SMOOTH_MKL_H_INCLUDED)
  #define COCG_LLT_SMOOTH_MKL_H_INCLUDED_REVERT
  #undef COCG_LLT_SMOOTH_MKL_H_INCLUDED
#endif

#define COCG_LLT_Smooth_MKL COCG_Di_Smooth_MKL

#include "COCG_LLT_Smooth_MKL.h"
#undef COCG_LLT_SMOOTH_MKL_H_INCLUDED

#undef COCG_LLT_Smooth_MKL

#if defined(COCG_LLT_SMOOTH_MKL_H_INCLUDED_REVERT)
  #define COCG_LLT_SMOOTH_MKL_H_INCLUDED
  #undef COCG_LLT_SMOOTH_MKL_H_INCLUDED_REVERT
#endif

#endif // COCG_DI_SMOOTH_MKL_H_INCLUDED
